// Central icon registry. Icons render in Phosphor's default "regular" weight.
// Duotone is reserved for the sidebar (see app-sidebar.tsx, which passes
// weight="duotone" explicitly) — don't default icons to duotone elsewhere.
export {
  SquaresFourIcon as SquaresFour,
  UsersIcon as Users,
  ArrowsLeftRightIcon as ArrowsLeftRight,
  CalculatorIcon as Calculator,
  ChartBarIcon as ChartBar,
  CaretDownIcon as CaretDown,
  CaretUpIcon as CaretUp,
  CaretRightIcon as CaretRight,
  WalletIcon as Wallet,
  ListIcon as List,
  XIcon as X,
  SignOutIcon as SignOut,
  PlusIcon as Plus,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowDownLeftIcon as ArrowDownLeft,
  ArrowLeftIcon as ArrowLeft,
  ScalesIcon as Scales,
  PencilSimpleIcon as PencilSimple,
  TrashIcon as Trash,
  PhoneIcon as Phone,
  CheckIcon as Check,
  CheckCircleIcon as CheckCircle,
  InfoIcon as Info,
  WarningIcon as Warning,
  XCircleIcon as XCircle,
  CircleNotchIcon as CircleNotch,
  ShieldCheckIcon as ShieldCheck,
  ShieldStarIcon as ShieldStar,
  DotsThreeVerticalIcon as DotsThreeVertical,
  ProhibitIcon as Prohibit,
  KeyIcon as Key,
  UserPlusIcon as UserPlus,
} from "@phosphor-icons/react/dist/ssr";
