// Central icon registry. Icons render in Phosphor's default "regular" weight.
// Duotone is reserved for the sidebar (see app-sidebar.tsx, which passes
// weight="duotone" explicitly) — don't default icons to duotone elsewhere.
export {
  SquaresFourIcon as SquaresFour,
  UsersIcon as Users,
  ArrowsLeftRightIcon as ArrowsLeftRight,
  CalculatorIcon as Calculator,
  ChartBarIcon as ChartBar,
  CaretDownIcon as CaretDown,
  CaretUpIcon as CaretUp,
  CaretRightIcon as CaretRight,
  WalletIcon as Wallet,
  UserCircleIcon as UserCircle,
  ListIcon as List,
  XIcon as X,
  SignOutIcon as SignOut,
  PlusIcon as Plus,
  ArrowUpRightIcon as ArrowUpRight,
  ArrowDownLeftIcon as ArrowDownLeft,
  ArrowLeftIcon as ArrowLeft,
  ScalesIcon as Scales,
  PencilSimpleIcon as PencilSimple,
  TrashIcon as Trash,
  PhoneIcon as Phone,
  CheckIcon as Check,
  CheckCircleIcon as CheckCircle,
  InfoIcon as Info,
  WarningIcon as Warning,
  XCircleIcon as XCircle,
  CircleNotchIcon as CircleNotch,
  ShieldCheckIcon as ShieldCheck,
  ShieldStarIcon as ShieldStar,
  DotsThreeVerticalIcon as DotsThreeVertical,
  ProhibitIcon as Prohibit,
  KeyIcon as Key,
  UserPlusIcon as UserPlus,
  // Files module
  FolderIcon as Folder,
  FolderOpenIcon as FolderOpen,
  FolderPlusIcon as FolderPlus,
  // Generic file glyph — keep the `Icon` suffix so it doesn't shadow the
  // global DOM `File` type used by the upload component.
  FileIcon,
  FileTextIcon as FileText,
  FilePdfIcon as FilePdf,
  FileZipIcon as FileZip,
  ImageIcon as FileImage,
  VideoCameraIcon as VideoCamera,
  MusicNotesIcon as MusicNotes,
  UploadSimpleIcon as UploadSimple,
  DownloadSimpleIcon as DownloadSimple,
  ArrowsOutCardinalIcon as ArrowsOutCardinal,
  EyeIcon as Eye,
  // Todos module
  ListChecksIcon as ListChecks,
  ClipboardTextIcon as ClipboardText,
  CircleIcon as Circle,
  CircleHalfIcon as CircleHalf,
  ClockIcon as Clock,
  CalendarBlankIcon as CalendarBlank,
  FlagIcon as Flag,
  // Notes module
  NoteIcon as Note,
  NotePencilIcon as NotePencil,
  PushPinIcon as PushPin,
  PushPinSlashIcon as PushPinSlash,
  ArchiveIcon as Archive,
  ArrowCounterClockwiseIcon as ArrowCounterClockwise,
  TagIcon as Tag,
  MagnifyingGlassIcon as MagnifyingGlass,
} from "@phosphor-icons/react/dist/ssr";
